sudo: required
services:
    - docker

before_install:
    - docker build -t bitstolearn/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true bitstolearn/react-test npm test

after_success:
    - docker build -t bitstolearn/multi-client ./client
    - docker build -t bitstolearn/multi-nginx ./nginx
    - docker build -t bitstolearn/multi-server ./server
    - docker build -t bitstolearn/multi-worker ./worker